### ISSUE TITLE
v2 roadmap

### ISSUE THREAD

**Issue by DamianOsipiuk** [DamianOsipiuk/vue-query#124]
# react-query/core

List of tickets in `react-query` V4 (not finalized): https://github.com/tannerlinsley/react-query/issues?q=is%3Aissue+label%3Av4+is%3Aclosed

- [x] https://github.com/tannerlinsley/react-query/pull/2988
- [x] https://github.com/tannerlinsley/react-query/pull/3071
- [x] Update docs
  - [x] https://github.com/tannerlinsley/react-query/pull/3006
  - [x] https://github.com/tannerlinsley/react-query/pull/2996
  - [x] https://github.com/tannerlinsley/react-query/pull/2937
  - [x] https://github.com/tannerlinsley/react-query/pull/2938
  - [x] https://github.com/tannerlinsley/react-query/pull/2963
  - [x] https://github.com/tannerlinsley/react-query/pull/2969
  - [x] https://github.com/tannerlinsley/react-query/pull/3223
  - [x] https://github.com/tannerlinsley/react-query/pull/3271
- [x] https://github.com/TanStack/query/pull/3834
- [x] https://github.com/TanStack/query/pull/3873
- [x] https://github.com/TanStack/query/pull/3988

# vue-query

- [x] hooks should wrap primitives as refs, but return functions as-is
  #123
- [x] create wrappers for `QueryClient`, `QueryCache`, `MutationCache` etc, so parameters could be passed as refs and would be automatically unwrapped
  #110
- [x] migrate devtools as a plugin to official vue devtools #155
- [x] nuxt 3 integration
- [ ] ~expose persistance plugins~ (This will be handled after migration to Tanstack)

# misc

- [x] Create migration to v2 page and notify about all noticeable changes in `react-query/core` and `vue-query`
- [ ] Consider codemods?

**Comment by DamianOsipiuk** [comment]
[v2.0.0-alpha.1](https://github.com/DamianOsipiuk/vue-query/releases/tag/v2.0.0-alpha.1)

**Comment by wobsoriano** [comment]
> [v2.0.0-alpha.1](https://github.com/DamianOsipiuk/vue-query/releases/tag/v2.0.0-alpha.1)

Thank you for this!

Where can we find types like `QueryFunctionContext`, `UseMutationResult`, etc. that can be imported in `vue-query/types`  before?

**Comment by wobsoriano** [comment]
@DamianOsipiuk  thank you for your great work!

**Comment by DamianOsipiuk** [comment]
@wobsoriano So, everything should be re-exported with [v2.0.0-alpha.3](https://github.com/DamianOsipiuk/vue-query/releases/tag/v2.0.0-alpha.3) - in case some types are still missing, please open a ticket.

**Comment by wobsoriano** [comment]
@DamianOsipiuk migrated one of my pet projects and all exported types are there now. Thanks!

**Comment by AndreyYolkin** [comment]
Happy to see that first beta appeared 🎉
Do you have any predictions on release date?

**Comment by Hawxy** [comment]
@DamianOsipiuk Could the type narrowing for `initialData` be included for v2? 
https://github.com/TanStack/query/issues/3310

**Comment by DamianOsipiuk** [comment]
> @DamianOsipiuk Could the type narrowing for `initialData` be included for v2? [TanStack/query#3310](https://github.com/TanStack/query/issues/3310)

Yes, all the changes introduced in v4 of react-query will be backported.


> Happy to see that first beta appeared 🎉 Do you have any predictions on release date?

Currently i'm trying to stabilize ESM support in [@tanstack/query](https://github.com/TanStack/query/issues/3882). When it will be done, i would have to go trough and backport all the changes that were done from the beta release. Probably then we could do a v2 release.

This package will be migrated as a part of https://github.com/TanStack/query. This will in turn bump the version to v4 to be in line the the core.
Question to the users. Do you prefer to
:one: Get v2 release sooner, followed up by v4 release under a different name (@tanstack/vue-query)
:two: Wait a little bit more for v4 directly.

**Comment by DamianOsipiuk** [comment]
Almost there... https://github.com/TanStack/query/pull/4254 🚀

**Comment by wobsoriano** [comment]
Appreciate your effort @DamianOsipiuk !

**Comment by DamianOsipiuk** [comment]
[@tanstack/vue-query](https://github.com/TanStack/query/tree/main/packages/vue-query) is now official. Thanks for the patience!
